[profile.default]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "openzeppelin-contracts/=lib/openzeppelin-contracts/",
  "@openzeppelin/=lib/openzeppelin-contracts/"
]
